### ISSUE TITLE
Wrong Booter Quirk for Cometlake Desktop

### ISSUE THREAD

**Issue by 5T33Z0** [Pavo-IM/OC-Gen-X#100]
Although the screenshot shows "SetupVirtualMap" as enabled [here](https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#booter)

It's later advised in the "More In-depth info", to set it to NO:

"SetupVirtualMap: **NO**

**Fixes SetVirtualAddresses calls to virtual addresses, however broken due to Comet Lake's memory protections. ASUS, Gigabyte and AsRock boards will not boot with this on."**

**Comment by errorexists** [comment]
take note that the dortania guide doesnt get update as it should be
