### ISSUE TITLE
Pull from existing config.plist

### ISSUE THREAD

**Issue by makeSmartio** [Pavo-IM/OC-Gen-X#103]
Great project! I just wanted to add a suggestion to be able to pull values from an existing plist - it would be so helpful for figuring out "what changed" 

Go ahead and close this issue. Cheers!

**Comment by errorexists** [comment]
what some of do is compare the sample plist with current to make proper changes

**Comment by makeSmartio** [comment]
Ahh, makes sense! Thanks for the tip!
