### ISSUE TITLE
Crashes when generating EFI

### ISSUE THREAD

**Issue by ArjixWasTaken** [Pavo-IM/OC-Gen-X#106]
I followed this video: https://www.youtube.com/watch?v=69T8RvlwT9s
I am on linux and I used [this](https://github.com/myspaghetti/macos-virtualbox) to run a VM in order to run this program.
The error logs were empty.

It did make an EFI folder, but I think that it's incomplete, here it  [is](https://github.com/Pavo-IM/OC-Gen-X/files/7756159/EFI_1.zip)

**Comment by errorexists** [comment]
read issue here https://github.com/Pavo-IM/OC-Gen-X/issues/105
