### ISSUE TITLE
CPU types for Mac Pro 4,1 and 5,1

### ISSUE THREAD

**Issue by 1900forever** [Pavo-IM/OC-Gen-X#108]
For now it's possible to configure Mac Pro 6,1 since it has Ivy-Bridge preset in OC-Gen-X.
However, if I need to work on older hardwares, like Westmere X5660 Xeon, I can't do it in OC-Gen-X, eventhough it has presets for Mac Pro 4,1 and 5,1.

It would be great this could be added.

**Comment by Pavo-IM** [comment]
I'll look at Dortania Guide and see if I can add it.
