### ISSUE TITLE
Gt640 Device missing

### ISSUE THREAD

**Issue by whenmusicattacks** [Pavo-IM/OC-Gen-X#110]
Hello! I have a Gt640 passive by Zotac, being a passive card i could really use a proper AGPM implementation but there is no entry in the OcGenX menu. I tried to guess it from the DeviceId i got from windows, but it shows as "0FC1" wich is not working when i modify the plist inside the Kext i generated for Gt730.

**Comment by Pavo-IM** [comment]
This is an older card that isn't supported before Catalina.

**Comment by whenmusicattacks** [comment]
Kepler is supported up to Big Sur in either Gk10x , gk110 and gk20x 
Do you care about actual facts or just want to close issues?
