### ISSUE TITLE
macOS12.3.1collapse

### ISSUE THREAD

**Issue by Eyeing-t** [Pavo-IM/OC-Gen-X#114]
macOS12.3.1collapse
Process:               OC_Gen-X [1871]
Path:                  /Applications/OC_Gen-X.app/Contents/MacOS/OC_Gen-X
Identifier:            com.oc-gen-x.OC-Gen-X
Version:               3.2.8 (3.2.8)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]

**Comment by errorexists** [comment]
unfortunately oc gen x has not been updated since January 11 with RL updates have been unable to be completed in the mean time go here for opencore 
https://dortania.github.io/builds/
thank you
