### ISSUE TITLE
Crash when generate EFI

### ISSUE THREAD

**Issue by TheNexter** [Pavo-IM/OC-Gen-X#117]
AMD ryzen 6 Cores
Lilu + virtual smc
whatevergreen
apple alc
realteakRTL8111

No more change

**Comment by b0gdanw** [comment]
Same

`Process:               OC_Gen-X [975]
Path:                  /Applications/OC_Gen-X.app/Contents/MacOS/OC_Gen-X
Identifier:            com.oc-gen-x.OC-Gen-X
Version:               3.3.1 (3.3.1)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           OC_Gen-X [975]
User ID:               501


OS Version:            macOS 11.6.8 (20G730)
Report Version:        12


System Integrity Protection: disabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes:       0x0000000000000001, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Illegal instruction: 4
Termination Reason:    Namespace SIGNAL, Code 0x4
Terminating Process:   exc handler [975]

`

**Comment by Pavo-IM** [comment]
Are both running it on BigSur on a bare metal system or VM?

**Comment by b0gdanw** [comment]
Not in VM, macOS 11.6.8 (20G730)

**Comment by Pavo-IM** [comment]
Have you verified you have something in the SMBIOS section before hitting the Generate button?

**Comment by Pavo-IM** [comment]
Can either of you test this version to see if it crashes.
[OC_Gen-X.zip](https://github.com/Pavo-IM/OC-Gen-X/files/9291269/OC_Gen-X.zip)

**Comment by b0gdanw** [comment]
SMBIOS was automatically filled in correctly.
The version above does not crash and generates the EFI folder.

**Comment by Pavo-IM** [comment]
Fixed and updated, open the current version of the app you have and Check for Updates to install the latest version that was just pushed. Will close for now, reopen if it happens again.

**Comment by TheNexter** [comment]
Ok it's working ;)
