### ISSUE TITLE
High Sierra Compatibility

### ISSUE THREAD

**Issue by sjsaes** [Pavo-IM/OC-Gen-X#119]
I've attempted to run this on my iMac to create an OC, and I errored out upon starting the pkg. The error says "Check with the developer to make sure OC_Gen-X works with this version of macOS". Nothing on the readme.md says anything about minimum version of macOS, so does it work with HS? Running 10.13.6. 

More error information:
> Termination Reason:    DYLD, [0x3] Wrong version

> Application Specific Information:
> dyld: launch, loading dependent libraries

> Dyld Error Message:
>  Library not loaded: @rpath/libswiftFoundation.dylib
>  Referenced from: /private/var/folders/*/OC_Gen-X.app/Contents/MacOS/OC_Gen-X
>  Reason: Incompatible library version: OC_Gen-X requires version 300.0.0 or later, but libswiftFoundation.dylib provides >version 1.0.0

**Comment by Pavo-IM** [comment]
Unfortunately this app requires Swift 5, which requires a minimum of 10.14.6
