### ISSUE TITLE
WebHook

### ISSUE THREAD

**Issue by Rescticed** [Pavo-IM/OC-Gen-X#15]
Hi Pavo,

Have you removed the webhook for OC-Gen X on the hackintoshx86 server
because if you have, I'm disappointed I've never said a bad word about you.
A whole community suffers because of a fallout, first big one in 18 months and now I'm the enemy
Almost 2 Years of friendship for nothing, I've had to post here as you've left me no other choice.

This doesn't need to be like this.

**Comment by phys1ks** [comment]
This doesn’t sound like an issue and sounds more like personal drama. I didn’t know I was on Facebook.

**Comment by Rescticed** [comment]
Well apologises, Pavo when you want to respond and have a proper conversation you know how to contact me.
