### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by Blurayx** [Pavo-IM/OC-Gen-X#16]
Can't wait to try this out but how do I launch OC-Gen-x?

Thanks

**Comment by Pavo-IM** [comment]
Well you download the release and click it to open it. It's just a regular macOS app.

**Comment by Blurayx** [comment]
Sorry I didn't see the release on the right

**Comment by chrisjenx** [comment]
@Blurayx yeah I was lost for a couple of days when GH changes everything around.

**Comment by Blurayx** [comment]
> @Blurayx yeah I was lost for a couple of days when GH changes everything around.
😂 
![default_thumbsup_anim](https://user-images.githubusercontent.com/2873112/87091140-146b8c00-c231-11ea-9054-4c8612bc0f49.gif)
