### ISSUE TITLE
Question about CPU selection

### ISSUE THREAD

**Issue by sonoseco** [Pavo-IM/OC-Gen-X#17]
First, thank you for such a great app. 

Does selecting a CPU make changes or apply quirks specific to the family of CPU selected? I have a Broadwell-E CPU (6950X) and using KVM, last time I tried to pass the CPU as host I could not boot the system, so I'm actually emulating a Skylake CPU.

**Comment by chrisjenx** [comment]
I haven't tried - but I think you would use host-passthrough so that you don't "emulate" the cpu with qemu/kvm. But I am far far from any authority on the matter. 
I.e. would love an answer from someone that knows far more than me :)

**Comment by Pavo-IM** [comment]
The app only generates a Qemu+Kvm for host CPU that was on a AMD system. but it can be adapted for Intel also.
