### ISSUE TITLE
Generated config file can't be opened by OpenCore Configurator

### ISSUE THREAD

**Issue by 1900forever** [Pavo-IM/OC-Gen-X#19]
Xcode can open it, everything else works fine

**Comment by errorexists** [comment]
opencore config tool should "NEVER" be used, use plist editor pro

**Comment by 1900forever** [comment]
found the problem, i manually added an entry, which shouldn't be existed in 0.6.0 version. my fault

**Comment by rasoolakhter** [comment]
I opened in textmate and only changed serial version uuid and everything thing worked and many thanks

[Akhter Rasool - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=mialx)	[mialx]

On August 4, 2020 at 0:41 GMT, 1900forever <notifications@github.com> wrote:

Closed [#19](https://github.com/Pavo-IM/OC-Gen-X/issues/19).

**Comment by LokiInside** [comment]
it can be opened but not all formating works
