### ISSUE TITLE
Is it possible to add support for version 13?

### ISSUE THREAD

**Issue by oncebeloved** [Pavo-IM/OC-Gen-X#20]
Due to the graphics driver, the system is still at version 13.6,It is recommended to add registration for minimum version 13.6

**Comment by Pavo-IM** [comment]
That is not a limitation on the app, its a limitation on your GPU selection. From my understanding OpenCore supports booting all the way down to 10.10, so this has nothing to do with the way the app generates your config. You will still need to make adjustments to the config that it generates no matter what.

**Comment by JokerHYC** [comment]
man,he means your oc-gen-x can't work at osx 13.6.....not oc...
