### ISSUE TITLE
Support in Mac OS X El Capitan 10.11.6

### ISSUE THREAD

**Issue by LocTran016** [Pavo-IM/OC-Gen-X#22]
Excuse me, I'm using a Macbook Pro 2009 (MacBookPro5,5) is there any way to make this support older version of MacOS: OS X El Capitan (10.11.6). Thanks for reading my issue
![image](https://user-images.githubusercontent.com/64778285/90765286-df645600-e313-11ea-97d5-be07846e0956.png)

**Comment by Pavo-IM** [comment]
The Codable protocol that is being used in the code requires at a minimum of Swift 4.2, which requires a minimum of 10.13.4. Sorry but that is the lowest I can go on supporting the usability of the app on older versions of MacOS.
