### ISSUE TITLE
Please Add AMD EFI Support

### ISSUE THREAD

**Issue by TurannUl** [Pavo-IM/OC-Gen-X#26]
To Kexts Tab SMCAMDProcessor and AMDRYZENCPUPowermanagement.kext

**Comment by Pavo-IM** [comment]
This is not a required kext, its optional. OC Gen-X will only have required kext built-in sorry.

**Comment by TurannUl** [comment]
Required For Power,SMC Management,I think one of the important kexts that should be

**Comment by Pavo-IM** [comment]
Negative, it is not required for power. It is an optional kext if you want to fine tune your CPU power, but it is not required in order to operate macOS.

**Comment by TurannUl** [comment]
I think I'll use OC Builder I liked this show man but now it's in the trash. https://imgyukle.com/i/x8dwhe

**Comment by Pavo-IM** [comment]
And that is your choice. Goodbye.
