### ISSUE TITLE
Laptop compatibility and windows app

### ISSUE THREAD

**Issue by chengziqaq** [Pavo-IM/OC-Gen-X#28]
1. Laptop compatibility
it seems to be not compatibilitable with laptop of kaby lake. 

2.  windows app
firstly, thank you for developing such a useful software. 

I sugggest that you can use another program language to develop this app so we can use it on macOS Windows even on linux. 

because many hackintosher did not have mac while they have windows.
but this app only work on macOS.

**Comment by Pavo-IM** [comment]
1.  There is no commonality with laptops, even if they are the same chipset and CPU, I will never add Laptop configs to this app. 
2. I only know the Swift language, if you know how to program the app in other languages that work with Windows or Linux by all means please do a PR.
