### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by bukyapavankumar** [Pavo-IM/OC-Gen-X#29]
I have a Dell Inspiron 3543 i5 5200u (broadwell)laptop
How can I generate efi

**Comment by TurannUl** [comment]
Use youtube

**Comment by bukyapavankumar** [comment]
I didn't find anything on YouTube

**Comment by Pavo-IM** [comment]
This app does not have predefined configs for laptops, I am not going to add laptop configs to this app.

**Comment by TurannUl** [comment]
https://youtu.be/75FbSemIWmI
