### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by TurannUl** [Pavo-IM/OC-Gen-X#30]
Add ROM field to SMBİOS tab

**Comment by Pavo-IM** [comment]
The ROM entry is not needed, this has been proven multiple times.

**Comment by TurannUl** [comment]
Okay

**Comment by Pavo-IM** [comment]
Added in 2.7.7 https://github.com/Pavo-IM/OC-Gen-X/commit/e79376f9c9d1c6300fc238afa5e48fa4c3d891e5
