### ISSUE TITLE
新EFI导致开机卡死情况

### ISSUE THREAD

**Issue by maomingyang1314** [Pavo-IM/OC-Gen-X#32]
尊敬的开发人员大大，我在使用您最新发布的oc genX时，我产生基于oc0.6.2的efi，但是在开机的时候一切正常，之后就开始卡死。不知道怎么回事，我和上一个版本设置的都是一样的呀。不知道为何会导致这个问题。烦请提示

**Comment by maomingyang1314** [comment]
Dear developer, when I used your newly released oc genX, I generated efi based on oc0.6.2, but everything was normal during the power-on self-check, and then it started to freeze. I don't know what's going on, I have the same settings as the previous version. I don't know why it causes this problem. Please remind

**Comment by Pavo-IM** [comment]
This is not a OC Gen-X issue, sound more like a config issue.
