### ISSUE TITLE
ACPI folder empty

### ISSUE THREAD

**Issue by quinton-ashley** [Pavo-IM/OC-Gen-X#34]
Thank you so much for making this app and making running macOS more accessible to people that don't have the IT/CS background necessary to follow the OC guide!

In the future will the app also generate the necessary aml files?

**Comment by Pavo-IM** [comment]
I have been thinking about this, but it will be awhile before I will do this because the current aml files need to be updated in order to facilitate all system types. But it is a feature that will be added later.

**Comment by mifjpn** [comment]
Great, Software!
Please consider adding ACPI in the future.
I tried it on Coffee lake, but the resulting EFI didn't work without it.
Basically, I hope it works if you don't modify config.plist later.
Also, I think it would be even more convenient if there was a function to import Kext, ACPI, and Tools from any folder and add them.

**Comment by errorexists** [comment]
you can also read the acpi guide to find what ssdt's you need for the acpi folder then add them to your config plist 
https://dortania.github.io/Getting-Started-With-ACPI/

**Comment by mifjpn** [comment]
Thank you for your quick response.
I copied and pasted the necessary items from ACPI and its Config.plist from the currently running OpenCore 0.6.4 EFI.
In that case, it works properly.
So this app is great!
To make it easier to write ACPI, Kext, efi (important is the difficulty of writing Kext), I hope this application supports it.
I could just copy and paste, but I think we use ProperTree  to put Kext in after.
Thank you.
