### ISSUE TITLE
Error: Bootloader Isn't Installed | NVRAM isn't native

### ISSUE THREAD

**Issue by frop14** [Pavo-IM/OC-Gen-X#36]
In Misc> Security> ExposeSensitiveData> value is wrong.

Oc Gen-X sets the value 8 which is wrong according to https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#misc
Value should be 6 and not 8

Config.plist> Misc> Security> ExposeSensitiveData>  6

**Comment by frop14** [comment]
> In Misc> Security> ExposeSensitiveData> value is wrong.
> 
> Oc Gen-X sets the value 8 which is wrong according to https://dortania.github.io/OpenCore-Install-Guide/config.plist/coffee-lake.html#misc
> Value should be 6 and not 8
> 
> Config.plist> Misc> Security> ExposeSensitiveData> 6

Excellent app by the way. Thank you

**Comment by Pavo-IM** [comment]
Thanks for the feedback and I will fix that mistake but I am not sure how that is related to the title of this issue you created.
