### ISSUE TITLE
open core version question

### ISSUE THREAD

**Issue by LastKing** [Pavo-IM/OC-Gen-X#37]
Dear developer.
I have a question. I use OC-Gen-X generate new efi. use the version
![image](https://user-images.githubusercontent.com/8540374/99020362-62a2ea00-2599-11eb-85a5-0ccf4ef31c92.png)

I change efi file and bootstrap system success,but i check opencore version is 0.6.1,i think the version should be 0.6.3.
![image](https://user-images.githubusercontent.com/8540374/99020414-89f9b700-2599-11eb-8c90-d34287c2a72d.png)

![image](https://user-images.githubusercontent.com/8540374/99020420-8ebe6b00-2599-11eb-86ca-894ff383fcae.png)

sorry Engilish is poor. Thank you very much.

**Comment by Pavo-IM** [comment]
The binaries that copied into the EFI Folder that gets generated are directly from OpenCorePkg GitHub repo, you must have forgotten to replace the OpenCore.efi file during copying.

**Comment by LastKing** [comment]
Thanks for your help.

OC-Gen-X the tool 
![image](https://user-images.githubusercontent.com/8540374/99082495-30c46e80-25ff-11eb-8211-5b2d40ebba55.png)

your repo the comment  `Updated to OpenCorePkg 0.6.3`
`BOOTx64.efi`  `Bootstrap.efi`  `OpenCore.efi` .

I just have question. 
Your repo already replace the binaries.
Your repo generate EFI folder  should include  newest open core.

Thank you.

**Comment by Pavo-IM** [comment]
Yes I download the official release from OpenCorePkg repo when they update them and add them to my app, so my app generates a EFI folder with the latest official releases of the binaries.

**Comment by Pavo-IM** [comment]
Just to let you know, I just generated a new EFI from the app and it indeed is 0.6.3.
![Screen Shot 2020-11-13 at 10 43 58 AM](https://user-images.githubusercontent.com/33814640/99091004-4acd6500-259d-11eb-8265-bb0e5a28eff8.png)

**Comment by LastKing** [comment]
Thank for your help.

I will check my config.  Thank you
