### ISSUE TITLE
Apps can't detect what bootloader I'm using

### ISSUE THREAD

**Issue by tommasobenatti** [Pavo-IM/OC-Gen-X#39]
Hackintool and OpenCore configurator can't detect the version of opencore that I'm using
![Schermata 2020-11-14 alle 03 11 31](https://user-images.githubusercontent.com/62927722/99136755-3170fb00-2627-11eb-84b4-3938f622ef7d.png)
![Schermata 2020-11-14 alle 03 11 56](https://user-images.githubusercontent.com/62927722/99136758-38980900-2627-11eb-8f4c-f7d6a0d99b1a.png)

**Comment by Pavo-IM** [comment]
Change `ExposeSensitiveData` to 10
