### ISSUE TITLE
Tool is not supported for old version of MacOS.

### ISSUE THREAD

**Issue by kennyluu123** [Pavo-IM/OC-Gen-X#42]
Hi there,

First of all, this ticket does not report a behavior issue. Just asking for a flavor.

Could you please support this tool for old version of MacOS?
Because I think there Manny hackintosh device still staying with old version same as mine. My system is macOS 10.12.6 but this tool requires at least macOS 10.13.

Best Regards,
TaiLuu

**Comment by errorexists** [comment]
refer to this closed post https://github.com/Pavo-IM/OC-Gen-X/issues/24
