### ISSUE TITLE
ForceResolution is needed?

### ISSUE THREAD

**Issue by zunda-pixel** [Pavo-IM/OC-Gen-X#44]
I make EFI Folder with OC-Gen-X
So I check config.plist with https://opencore.slowgeek.com/

Result
Output
You should have exactly 12 settings in the UEFI/Output section
[ForceResolution is missing. Normally set to No]
ForceResolution is needed in OpenCore v0.6.3?

<img width="300" alt="スクリーンショット 2020-11-20 6 28 18" src="https://user-images.githubusercontent.com/47569369/99726273-a053c580-2af9-11eb-85dc-d6e9aba49fd7.png">

**Comment by Pavo-IM** [comment]
Thanks for the feedback, fixed in 2.6.6, check for updates within the app to pull the latest version.

**Comment by rowild** [comment]
Sanity Checker shows this error (again?) when using OpenCore 0.6.7

**Comment by TypeChecked-RBX** [comment]
Just to be clear, if I'm getting this while following the OpenCore guide, without messing with any of the settings in UEFI/Output, I'm good to go?

**Comment by MrNobody326** [comment]
I have the same problem. :(
