### ISSUE TITLE
some item is not default .

### ISSUE THREAD

**Issue by zunda-pixel** [Pavo-IM/OC-Gen-X#45]
almost the same issue https://github.com/Pavo-IM/OC-Gen-X/issues/44
I created EFI Folder with OC-Gen-X v2.6.6
So I checked config.plist with https://opencore.slowgeek.com/

# Result

## Booter>MmioWhitelist>Quirks

AvoidRuntimeDefrag = No but should normally be Yes
EnableSafeModeSlide = No but should normally be Yes
ProtectUefiServices = No but should normally be Yes
ProvideCustomSlide = No but should normally be Yes
SetupVirtualMap = No but should normally be Yes

## Force>Patch>Quirks

AppleCpuPmCfgLock = Yes but should normally be No

## CustomMemory > Generic

SpoofVendor = No but should normally be Yes
SystemMemoryStatus = -blank- but should normally be Auto

# Problem
ProtectUefiServices is NO on official OpenCore v0.6.3's sample.plist
maybe https://opencore.slowgeek.com/ is wrong in ProtectUefiServices

**Comment by Pavo-IM** [comment]
What system type?

**Comment by zunda-pixel** [comment]
Core i7 8700 (Desktop: (8th, 9th Gen) Coffee Lake)

**Comment by Pavo-IM** [comment]
> ## Booter>Quirks
> AvoidRuntimeDefrag = No but should normally be Yes
> EnableSafeModeSlide = No but should normally be Yes
> ProtectUefiServices = No but should normally be Yes
> ProvideCustomSlide = No but should normally be Yes
> SetupVirtualMap = No but should normally be Yes
Ok I will fix `AvoidRuntimeDefrag` to be `Yes` but the guide does state anything for `EnableSafeModeSlide` which I assume means disabled. The guide states `ProtectUefiServices` should be `No` unless on Z390, so if you are on a Z390 you can turn that on yourself. `ProvideCustomSlide` should be `No` and `SetupVirtualMap` should not be enabled with `RebuildAppleMemoryMap` enabled. 
> ## Kernel>Quirks
> AppleCpuPmCfgLock = Yes but should normally be No
`AppleCpuPmCfgLock` should be enabled unless you can disable `CFG-Lock` ion BIOS, which most BIOS do not give this option and does effect anything even if its enabled and `CFG-Lock` is disabled in BIOS.
> ## PlatformInfo > Generic
> SpoofVendor = No but should normally be Yes
> SystemMemoryStatus = -blank- but should normally be Auto
`SpoofVendor` is personal choice, me personally do not like to spoof the vendor of my motherboard. I will fix `SystemMemoryStatus` to be `Auto`

**Comment by zunda-pixel** [comment]
Thanks!

**Comment by Pavo-IM** [comment]
Fixed in https://github.com/Pavo-IM/OC-Gen-X/commit/a8c35cffd37c7b3af5f33c548ce347838d63069f wait 10 minutes and Check for updates within the app to pull latest release.
