### ISSUE TITLE
Its not an issue but could you add Broadwell please

### ISSUE THREAD

**Issue by TaminoPalm** [Pavo-IM/OC-Gen-X#46]
That would be so nice!

**Comment by Pavo-IM** [comment]
There is no guide for Broadwell.

**Comment by TaminoPalm** [comment]
Hello, there is a guide here:

https://dortania.github.io/OpenCore-Install-Guide/config-laptop.plist/broadwell.html

I would love to have this integrated to support my Broadwell based Intel NUC.

**Comment by Pavo-IM** [comment]
That is for laptops, this app is only for desktops. This app will only have desktop support, I am not including laptop or AIO configurations sorry.

**Comment by TaminoPalm** [comment]
I and my NUC would appreciate it ;)
