### ISSUE TITLE
未支持Ivy Bridge-E架构

### ISSUE THREAD

**Issue by adminliux** [Pavo-IM/OC-Gen-X#48]

**Comment by Pavo-IM** [comment]
Ok..... and what is the issue?

**Comment by adminliux** [comment]
没有其他的问题我是x79平台 我按照 [ivy-bridge-e安装文档](https://dortania.github.io/OpenCore-Install-Guide/config-HEDT/ivy-bridge-e.html#starting-point)制作了一份EFI始终卡在eb出我想试试此工具是个可行。

**Comment by Pavo-IM** [comment]
You need to put your issue in English, I can not help you if I can not understand you.

**Comment by thomas22122212** [comment]
I guess he's asking for Ivybridge-E(P) and probably Sandybridge-E(P) support. These are HEDT Systems based on X79 Chipset and LGA2011 Sockets. As they offer good performance and low secondhand prices they are still fairly popular. This platform is quite similar to MacPro6,1 (trashcan).
I am using a P9X79 WS board with an Intel 1650v2 but still on Catalina + Clover. An updated version of OC-Gen-X with support for Ivybridge HEDT would really help doing the migration to BigSur+Opencore

**Comment by Pavo-IM** [comment]
Ok I can add the settings from this guide

**Comment by thomas22122212** [comment]
Do you know how long this will approximately take you? I'd really like to test it

**Comment by Pavo-IM** [comment]
I'll look at adding it this weekend.

**Comment by Pavo-IM** [comment]
Added.... https://github.com/Pavo-IM/OC-Gen-X/commit/d55c11773d41039f22c83aa8ffac6eded0dd9d2e
