### ISSUE TITLE
Please add ACPI(SSDT) Settings

### ISSUE THREAD

**Issue by zunda-pixel** [Pavo-IM/OC-Gen-X#50]
OC-Gen-X default ACPI settings is nothing.

Please add ACPI(SSDT) Settings(config.plist) and enable download ACPI

https://dortania.github.io/Getting-Started-With-ACPI/ssdt-platform.html#desktop

**Comment by Pavo-IM** [comment]
ACPI tables is a complex problem and in order to provide the correct solution it would require something I am still trying to figure out. I will add ACPI table features once I have figured that solution out, simply adding a feature to download pre-made ones is not the correct solution.

**Comment by zunda-pixel** [comment]
Thanks
