### ISSUE TITLE
this not an issue. what about adding sandy bridge in your app? 

### ISSUE THREAD

**Issue by alamelin** [Pavo-IM/OC-Gen-X#51]

**Comment by Pavo-IM** [comment]
Does your desktop motherboard support UEFI?

**Comment by tommasobenatti** [comment]
I can confirm that some mobo with 1155 support UEFI like the dell optiplex 7010 that supports sandy and ivy bridge

**Comment by crojack** [comment]
Please Pavo, there are many of us who have SandyBridge.
I have HP Z420, UEFI, Intel Xeon E-1620 SandyBridge, Chipset C600/X79, AMD Radeon RX570. I run OpenCore 0.6.3 with BigSur, but it would be much easier to upgrade OpenCore with OC GenX.

**Comment by Pavo-IM** [comment]
I will add the SandyBridge feature in the next update.
