### ISSUE TITLE
Add support to Penryn Architecture

### ISSUE THREAD

**Issue by EarlyGamer45** [Pavo-IM/OC-Gen-X#53]
Hi, how can i create my EFI based on Penryn architecture?
I know that app can create automatically a EFI but there's no support for that architecture.
is possibile to add the support for that?  it would be useful for people.... 
I have a intel core dual duo P8600 and i would like to create a EFI with that tool...
It will be more easy to do... 
I know that i can install MacOS High Sierra on that.
Regards...

**Comment by Pavo-IM** [comment]
Does your motherboard support UEFI?

**Comment by EarlyGamer45** [comment]
Nope, it doesn't.

**Comment by Pavo-IM** [comment]
Adding non-UEFI support is not planned at this time sorry.
