### ISSUE TITLE
USBInjectAll is not up to date

### ISSUE THREAD

**Issue by mavisguo** [Pavo-IM/OC-Gen-X#60]
USBInjectAll.kext is not up to date.The latest vesion is 0.7.6 but auto generated is 0.7.1.

**Comment by Pavo-IM** [comment]
Do you have the GitHub or Bitbucket location of the source code for the latest version? Only kext with verifiable source code will be added to the app.

**Comment by mavisguo** [comment]
I knew that and I always update my kexts by Kext_Updater.

**Comment by Pavo-IM** [comment]
Kext_Updater isn't a verifiable open source code.

**Comment by mavisguo** [comment]
Oh,I see.

**Comment by Pavo-IM** [comment]
Sorry, I only add kext that have a open source code that anyone using the app can go check the source code of the kext that it installs.

**Comment by mavisguo** [comment]
you are right.
