### ISSUE TITLE
Generate EFI button is disable

### ISSUE THREAD

**Issue by Paras-Chodavadiya** [Pavo-IM/OC-Gen-X#61]
Even after selecting all necessary options, the Generate EFI button is not enabling.
Please guide me if I am following any wrong method.
Kindly check the image:
![Screenshot 2021-01-20 at 11 36 51 AM](https://user-images.githubusercontent.com/589514/105134069-d5898d80-5b13-11eb-94c5-e691b92556c1.png)

**Comment by Pavo-IM** [comment]
Did you click the refresh button in the SMBIOS section?

**Comment by Pavo-IM** [comment]
I'll push an update to the Readme for the instructions, thanks for the feedback, glad its working for you now.
