### ISSUE TITLE
SMBIOS -> System Model

### ISSUE THREAD

**Issue by BrandTime** [Pavo-IM/OC-Gen-X#66]
Why does the SMBIOS System Model have no MacBookPro11,4 option ? (Ver2.9.4)

**Comment by Pavo-IM** [comment]
Because this app is for Desktop hackintoshes, not laptops.

**Comment by frankstallone** [comment]
> Because this app is for Desktop hackintoshes, not laptops.

That should be in the description/readme if it isn't.

**Comment by Pavo-IM** [comment]
It is, people just don't know how to read.
