### ISSUE TITLE
boot err，lilu disabling user patcher on request

### ISSUE THREAD

**Issue by einsqing** [Pavo-IM/OC-Gen-X#67]
![1651613644091_ pic](https://user-images.githubusercontent.com/7685948/108343642-270e6080-7217-11eb-9c96-ec27c5423935.jpg)

[EFI.zip](https://github.com/Pavo-IM/OC-Gen-X/files/6002078/EFI.zip)

**Comment by Pavo-IM** [comment]
What system type did you select and what macOS version are you trying to boot?

**Comment by einsqing** [comment]
![Uploading IMG_20210218_211347.jpg…]()

**Comment by einsqing** [comment]
skylake，bugsur 11.2，A new problem has cropped up

**Comment by Pavo-IM** [comment]
Not sure if the `-lilubeta`  is related or not, but you don't need it for 11.2. I will have to find another user to validate if there is any issues with the config settings that the app is generating.

**Comment by einsqing** [comment]
With or without -lilubeta, they are all dead.I have tried many times

**Comment by einsqing** [comment]
select ReleaseUsbOwnership is ok
