### ISSUE TITLE
100% use SSD disk on ivybridge desktop at last version

### ISSUE THREAD

**Issue by enckyridion** [Pavo-IM/OC-Gen-X#68]
Hello, I have my disk at 100% recording usage when using the latest version of open core on my IvyBridge Desktop ...

B75-D3H
I5 3570K
RX 560 SAPPHIRE
8 RAM
128 GB SSD.

I even noticed that in just 2 minutes with the system idle, the disk had a recording of 5 GB ... When looking at the disk manager, there is no process consuming disk band. NOTE: Clean installation done.

**Comment by Pavo-IM** [comment]
Without seeing this in Activity Monitor, not much I can do confirm this issue. As you can see from my screenshot, it only used 1.3 MB of disk read usage and 0 write.
![Screen Shot 2021-02-20 at 4 33 27 PM](https://user-images.githubusercontent.com/33814640/108609095-9a3fe000-7399-11eb-9bd5-59d6b4281259.png)

**Comment by Pavo-IM** [comment]
If you are referring to OpenCore itself, that is an issue you would need to point out to the Acidanthera dev team on their bug tracker https://github.com/acidanthera/bugtracker/issues

**Comment by enckyridion** [comment]
First of all I would like to thank you for the quick feedback on the message. Okay, I'm going to do that now, thank you very much for your time and attention.
