### ISSUE TITLE
Update Error!

### ISSUE THREAD

**Issue by xilliofeqast** [Pavo-IM/OC-Gen-X#71]
"An error occurred while running the updater. Please try again later."

This error message showed up when I tried to update from 2.9.4 to 2.9.5.

**Comment by errorexists** [comment]
just download new version an replace yours this happens from time to time

**Comment by Pavo-IM** [comment]
For some reason the Sparkle appcast cert got revoked since the last version. You will need to download the latest app manually. Sorry for the inconvenience .
