### ISSUE TITLE
require support a very popular kext

### ISSUE THREAD

**Issue by Petelin** [Pavo-IM/OC-Gen-X#73]
this is a project support wireless intel WIFI

https://github.com/OpenIntelWireless/itlwm

**Comment by errorexists** [comment]
wifi kexts are not supported as they are not added to the opencore package as the same goes for any laptops thewy will not be supported on the app 
Important Information (Please read below)

This app is only for desktop hackintosh machines, it does not have any pre-defined settings for laptop hackintosh machines.

**Comment by Petelin** [comment]
it is not for laptops, i am using [ax200](https://ark.intel.com/content/www/us/en/ark/products/189347/intel-wi-fi-6-ax200-gig.html) on my MSI B460, it is really cool project.

**Comment by errorexists** [comment]
be more reasonable to use a fenvi card or chip i have both an never any issues as neither need kexts

**Comment by Pavo-IM** [comment]
This kext makes the wifi act as a ethernet and doesn't work with macOS's internal WiFi settings. If it every gets fixed to work as a WiFi device I will consider adding it, but until that happens I will not.
