### ISSUE TITLE
Area under AGPMInjector Blank

### ISSUE THREAD

**Issue by AvaQueen-Official** [Pavo-IM/OC-Gen-X#77]
![Screen Shot 2021-04-11 at 10 19 51 AM](https://user-images.githubusercontent.com/79278890/114307861-89653e00-9aaf-11eb-8f92-73429c0cffeb.png)

**Comment by Pavo-IM** [comment]
What all are you selecting?

**Comment by AvaQueen-Official** [comment]
When I select it still shows blank. idk if it's just me but that's what it does

**Comment by Pavo-IM** [comment]
What all are you selecting prior?

**Comment by AvaQueen-Official** [comment]
I select WhateverGreen then this. Let me see if its just something with this specific app and download again.

**Comment by AvaQueen-Official** [comment]
Update: new app - no problem. Sorry about that. Next time if I find something I'll see if the issue duplicates
