### ISSUE TITLE
Development version of Opencore

### ISSUE THREAD

**Issue by iMonZ** [Pavo-IM/OC-Gen-X#86]
Add a function for installing a development version of Open core and the kext like you could in ocbuilder.
Or maybe including the ocbuilder script so you can build everything for yourself

**Comment by Pavo-IM** [comment]
This app is specifically made for the official release of OpenCorePkg. You can always use ocbuilder to do what you are asking.

**Comment by iMonZ** [comment]
> This app is specifically made for the official release of OpenCorePkg. You can always use ocbuilder to do what you are asking.

Ocbuilder is not updated anymore :(

**Comment by Pavo-IM** [comment]
> 
> Ocbuilder is not updated anymore :(

It doesn't need to be updated, it still works, just ran it on Monterey.
