### ISSUE TITLE
Wrong Kernel Quirk set in Cometlake Config

### ISSUE THREAD

**Issue by 5T33Z0** [Pavo-IM/OC-Gen-X#90]
I've noticed that the `AppleCpuPmCfgLock` Quirk is enabled in the Cometlake Config. This Quirk is for older CPUs which use legacy Power Management (up to IvyBridge).  If you have a look in the Installation Guide for Cometlake, you'll notice that this is disabled: https://dortania.github.io/OpenCore-Install-Guide/config.plist/comet-lake.html#kernel

**Comment by Pavo-IM** [comment]
Fixed in 3.1.7, thanks for the feedback.
