### ISSUE TITLE
Missing Keys in OC 0.7.2 Config

### ISSUE THREAD

**Issue by 5T33Z0** [Pavo-IM/OC-Gen-X#92]
Hi. I just generated a config for Coffeelake using OC Gen X and noticed some missing keys. They are:

- Kernel > Scheme > CustomKernel
- UEFI > AppleInput > GraphicsInputMirroring

Probably affects configs for other CPU families, too

**Comment by AnubisGreat** [comment]
Come back as soon as you can. I have started my Opencore adventures long time ago with your software! At that time it helped me a lot :)

**Comment by fjelgar** [comment]
Echo that. Looking forward to your updates, with many thanks.
