### ISSUE TITLE
VEGA64 Patch

### ISSUE THREAD

**Issue by legendprime** [Pavo-IM/OC-Gen-X#93]
You might look at the recent patches that allow the VEGA64 cards to work on iMacPro1,1 identifiers:
https://github.com/dortania/OpenCore-Legacy-Patcher/commits/main

At first VEGA64 wasn't working with more than 2 displays, but now all displays power. Apparently this is a kind of rare bug but happens with the iMacPro1,1 when used.

**Comment by Pavo-IM** [comment]
Use WhateverGreen
