### ISSUE TITLE
HP Elite 8300

### ISSUE THREAD

**Issue by legendprime** [Pavo-IM/OC-Gen-X#94]
There are a lot of HP Elite 8300 users, could you please tweak the kext options and any settings here that might help line up better with the success of people like this?:

- https://github.com/Sniki/HP6300-HP8300/tree/main/EFI/OC/Kexts
- https://github.com/blacklizard/Hackintosh-Opencore-Guide-HP8300-SFF-i5-3470-Catalina

I'm not sure but I think I can use USBInjectAll instead of USBPorts, but I'm not sure.

**Comment by errorexists** [comment]
USBInjectAll  is to open all ports on the mcahine USBPorts is for mapped if you want to mapp your own ports you must have usbijectall then you can choose the ports you want
