### ISSUE TITLE
EnableWriteUnprotector for  Coffee Lake architecture

### ISSUE THREAD

**Issue by xmh0511** [Pavo-IM/OC-Gen-X#97]
Seems that the item **EnableWriteUnprotector** should be true on Coffee Lake architecture. If we set its value to be false, we will be stuck at the "Macos version Not set yet" step.

**Comment by Pavo-IM** [comment]
Not according to the Dortania Guide, which is what this app is based off of.
![Screen Shot 2022-01-11 at 4 44 07 PM](https://user-images.githubusercontent.com/33814640/149026191-167b0f95-e9bd-4181-9ee2-cafcfc1f4138.png)
