### ISSUE TITLE
OC_Gen-X and OC 0.7.3 and beyond not compatible

### ISSUE THREAD

**Issue by Rositani** [Pavo-IM/OC-Gen-X#98]
Are you working on updating Gen-X to the new Open Core packages as they are array-based and config.plist created by the current version will not work with the newer OC packages?
Drivers section in config.plist is now array-based, not string-based.
Drivers now have “enabled” and path(s) so update your config.plist

**Comment by errorexists** [comment]
be patient as pavo is busy with personal life agendas

**Comment by Pavo-IM** [comment]
Updated
